#! /bin/bash

# (c) Thomas Lange, 2001-2017, lange@debian.org

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

ifclass XORG && {
    fcopy -M /etc/X11/xorg.conf
}

if ifclass UBUNTU; then
     groups="adm cdrom sudo dip plugdev lpadmin sambashare"
     $ROOTCMD addgroup --system lpadmin || true
     $ROOTCMD addgroup --system sambashare || true
fi

# add additional user account
if [ -n "$username" ]; then
    if ! $ROOTCMD getent passwd $username ; then
	$ROOTCMD adduser --disabled-login --gecos "$username user" $username
	$ROOTCMD usermod -p "$USERPW" $username
	userdir=$($ROOTCMD getent passwd "$username" | cut -d: -f6 )

	# disable xfce question about default or empty panel
	if [ -f $target/etc/xdg/xfce4/panel/default.xml ]; then
	    xfdir=$userdir/.config/xfce4/xfconf/xfce-perchannel-xml
	    if [ ! -d $target/$xfdir ]; then
		$ROOTCMD mkdir -p $xfdir
		$ROOTCMD cp /etc/xdg/xfce4/panel/default.xml $xfdir/xfce4-panel.xml
		# group name is the same as user name
		$ROOTCMD chown -R $username.$username $userdir/.config
	    fi
	fi

	for g in $groups; do
	    $ROOTCMD adduser $username $g
	done
    fi
$ROOTCMD echo -n '$username:$username' | chpasswd
$ROOTCMD echo '$username ALL = NOPASSWD: ALL' > /etc/sudoers.d/vagrant
$ROOTCMD chmod 440 /etc/sudoers.d/vagrant
$ROOTCMD mkdir -p $userdir/$username/.ssh
$ROOTCMD chmod 700 $userdir/$username/.ssh
$ROOTCMD echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ==" > $userdir/$username/.ssh/authorized_keys
$ROOTCMD chmod 600 $userdir/$username/.ssh/authorized_keys
$ROOTCMD mkdir -p $userdir/$username/belin-live
$ROOTCMD cd $userdir/$username
$ROOTCMD git clone https://salsa.debian.org/belin-team/belin-live
$ROOTCMD chown -hR $username:$username $userdir
$ROOTCMD sed -i -e 's/Defaults.*requiretty/#&/' /etc/sudoers
$ROOTCMD sed -i -e 's/\(UsePAM \)yes/\1 no/' /etc/ssh/sshd_config
$ROOTCMD mkdir -p /var/run/sshd
fi
