#!/bin/bash
set -e
echo A felhasználó neve $username
echo HOME könyvtár: $userdir
echo a Target rendszer $target
echo a root parancs $ROOTCMD
echo A fájlok listája:
ls $target
$ROOTCMD mkdir  etc/sudoers.d
$ROOTCMD echo '$username ALL = NOPASSWD: ALL' >etc/sudoers.d/vagrant
$ROOTCMD chmod 440 etc/sudoers.d/vagrant
$ROOTCMD mkdir $userdir/.ssh
$ROOTCMD chmod 700 $userdir/.ssh
$ROOTCMD echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ==" > $userdir/.ssh/authorized_keys
$ROOTCMD chmod 600 $userdir/.ssh/authorized_keys
$ROOTCMD mkdir -p $userdir/belin-live
$ROOTCMD cd $userdir
$ROOTCMD git clone https://salsa.debian.org/belin-team/belin-live
$ROOTCMD chown -hR $username:$username $userdir
$ROOTCMD sed -i -e 's/Defaults.*requiretty/#&/' etc/sudoers
$ROOTCMD sed -i -e 's/\(UsePAM \)yes/\1 no/' etc/ssh/sshd_config
$ROOTCMD mkdir -p /var/run/sshd